kind: component
version: 1.1

name: "training"

inputs:
- {name: nr_epochs,       type: int,   isOptional: true, value: 100}
- {name: nr_epochs_torch, type: int,   isOptional: true, value: 10 }
- {name: lrate,           type: float, isOptional: true, value: 0.01}
- {name: experiment,      type: str,   isOptional: false }
- {name: noise_var,       type: float, isOptional: true, value: 0.1}
- {name: loss_type,       type: str,   isOptional: true, value: kld}
- {name: training_type,   type: str,   isOptional: true, value: Q_training}
- {name: run_name,        type: str,   isOptional: true, value: wandb_run_name}
- {name: seed,            type: int,   isOptional: true, value: 117}
- {name: extra_n,         type: int,   isOptional: true, value: 0}
- {name: extra_L,         type: int,   isOptional: true, value: 0}

run:
  kind: job
  environment:
    labels:
      owner: rafal.nowak  # internal Polyaxon username
    securityContext:
      runAsGroup: 2222
      runAsNonRoot: true
      runAsUser: 2222

#  connections:
#    - cluster-polyaxon-datasets
#    - cluster-polyaxon-users

  container:
    image: 172.30.0.8:49154/r-hmm-flow/baseline:ver2
    imagePullPolicy: IfNotPresent # or Always
    resources:
      limits:
        nvidia.com/gpu: 1
    workingDir: "{{ globals.run_artifacts_path }}/uploads"
    command: [ "python", "flowhmm/main2d.py" ]
    args: [
        "--nr_epochs={{ nr_epochs }}",
        "--nr_epochs_torch={{ nr_epochs_torch }}",
        "--lrate={{ lrate }}",
        "--example_yaml={{ experiment }}",
        "--add_noise",
        "--noise_var={{ noise_var }}",
        "--training_type={{ training_type }}",
        "--loss_type={{ loss_type }}",
        "--output_file=output.pkl",
        "--seed={{ seed }}",
        "--extra_n={{ extra_n }}",
        "--extra_L={{ extra_L }}",
        "--polyaxon",
        "--show_plots",
        "--use_wandb_logging",
        "--run_name={{ run_name }}",
    ]
    env:
      - name: GIT_PYTHON_REFRESH
        value: quiet
      - name: HOME
        value: '{{ globals.run_outputs_path }}'
      - name: PYTHONPATH
        value: 'flowhmm:.'
      - name: WANDB_API_KEY
        value: PUT_WANDB_API_KEY_HERE
